### ISSUE TITLE
DOCUMENTATION

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#100]
Ok, version one is coming together... now need some better documentation on starting an instance and connecting devices.
- [x] Quick start guide
- [x] Links to microcontroller examples
- [x] Grow.js documentation published on gh-pages
- [ ] Diagram of architecture
- [ ] Better document the Meteor API
- [ ] Explore meteor documentation tools (any suggestions?)

**Comment by elsehow** [comment]
Would be great to have a quickstart in the README, something I could copy-paste to see what this library does / how it works.

**Comment by JakeHartnell** [comment]
Yes, I'm working on that currently. I have May 19th targeted for an Alpha release date!

**Comment by JakeHartnell** [comment]
Documentation is a never ending process. Closing this for now, let me know if there are things that could be better and I'll do my best to improve the docs.
