### ISSUE TITLE
First-time setup experience

### ISSUE THREAD

**Issue by elsehow** [CommonGarden/Grow-IoT#135]
## setting up repo think-aloud
- why do i need to make an account on my own local server?
- seems like Quyickstart is redudnant with the first part. on closer inspection, it's actually redundant with the grow.js repo quickstart, which is confusing, because that repo isn't linked to at all. IMO, it should just point me toward Grow.JS and tell me to set it up. 
- alternatively, why do i need to set anything else up? shouldn't Grow-IoT just install grow.js for m- e?
- ok, now i'm reading over the example.js and i'm still not understanding on a high level what's going on. what is this script an exampel of? a device? a plant? i am kind of gathering that it defines stuff in an IFTTT kind of way (why am i not just using IFTTT, by the way?)
- ok, sick, so now there's this nice looking UI, and it's very obvious why this might be easier than IFTTT for my usecase.  I wish this screenshot came earlier, with a little description of what this package _really does_
## overall notes

in the README now,  the text under "An extensible, opens ource IoT Pub/Sub Stack" is not concrete enough to be informative (and, it sounds like a lot of other things that are out there). considering the project is called Grow-IoT, i think the gardening use case should be mentioned front and center pretty much, with this screenshot at the top and a couple sentences about why this is the app for me.

eventually, it would be great to see a UI where GrowIoT could generate those grow.js files under the hood. it's definitely great to have a plaintext layer, and I think GrowIoT should continue to support text scripting, but for now the interaction feels about 10x harder than using IFTT.

overall, UI looks great. am going to open up a few issues now, and will issue a PR with README updates sometime in the next couple hours.

**Comment by JakeHartnell** [comment]
Quick note for now: THANK YOU! Let's keep the thoughts and feedback coming. : )

**Comment by JakeHartnell** [comment]
Thanks for the thoughts again... I'm going to take another stab at docs soon. Closing.
