### ISSUE TITLE
Grow-IoT could generate grow.js files under the hood

### ISSUE THREAD

**Issue by elsehow** [CommonGarden/Grow-IoT#140]
referencing #135 

Some UI for generating grow.js files could be good.

it's definitely great to have a plaintext layer, and I think GrowIoT should continue to support text scripting, but for now it's a bit of overhead to write the files.

**Comment by JakeHartnell** [comment]
> Some UI for generating grow.js files could be good.

+1

**Comment by JakeHartnell** [comment]
I'm going to close this as the data model should stabilize a bit before we start making UI for creating custom devices. Leaving #135 open as a thread for more commentary on the prototype.
