### ISSUE TITLE
When not logged in, redirect to login page

### ISSUE THREAD

**Issue by cloudzombie** [CommonGarden/Grow-IoT#162]
Meteor App is there, but does not initialize properly, none of the routes are rendering in the view properly.

**Comment by JakeHartnell** [comment]
What's in the console? Are you running the most recent master branch?

**Comment by JakeHartnell** [comment]
Ah, I think this is a routes issue. It should redirect to the login page.

**Comment by JakeHartnell** [comment]
Ok, on the latest master, I'm not having that problem. Is your master branch up to date? Try `git pull --rebase origin master`

I'm closing this for now, feel free to reopen if the problem still persists...
