### ISSUE TITLE
Convert 'core' package to ES6

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#181]
It's the only remaining plugin in coffeescript. Might provide some good examples for https://github.com/peerlibrary/meteor-peerdb/issues/30?

**Comment by mitar** [comment]
Hm, not really. Feel free to make it. :-)

**Comment by JakeHartnell** [comment]
Ok, I'll give it a shot.

**Comment by JakeHartnell** [comment]
https://github.com/CommonGarden/Grow-IoT/pull/189

**Comment by JakeHartnell** [comment]
I give up. This is not so important for now...
