### ISSUE TITLE
App 'Not Found' 

### ISSUE THREAD

**Issue by cloudzombie** [CommonGarden/Grow-IoT#187]
This is what I see on recent pull from `master`branch on the view routes. 

![login not found](https://cloud.githubusercontent.com/assets/8473624/15934466/91d2d452-2e18-11e6-8ce8-0b7fe5709b31.PNG)

![grow-iot home not found](https://cloud.githubusercontent.com/assets/8473624/15934505/abbd1026-2e18-11e6-8efe-1856401b32df.PNG)

The `Development` branch still works as desired for now, but I can't seem to find out why the master is doing that.

**Comment by JakeHartnell** [comment]
1. Right click
2. Inspect (this pops open the developer console)
3. Are there any errors there?

**Comment by JakeHartnell** [comment]
Try the latest master, and let me know if the issue is resolved. : )

**Comment by JakeHartnell** [comment]
This might be the same issue as #191. Try `npm install`, and let me know if that solves the problem.

**Comment by JakeHartnell** [comment]
Alright, I'm 95% sure this is related to #191 and is my fault because I didn't update the instructions when I added the later.js npm package. Feel free to reopen if this is still an issue.
