### ISSUE TITLE
laterjs not found

### ISSUE THREAD

**Issue by EdwardKepler** [CommonGarden/Grow-IoT#191]
<img width="1213" alt="screen shot 2016-06-15 at 9 08 37 am" src="https://cloud.githubusercontent.com/assets/15167277/16083019/2197cf24-32d9-11e6-942e-cf82f74b37d8.png">

**Comment by JakeHartnell** [comment]
@EdwardKepler  try `npm install`?

**Comment by JakeHartnell** [comment]
Closing as I'm fairly certain this the fault of my faulty instructions. Meteor is a little confusing as it supports two packaging systems [atmosphere](https://atmospherejs.com/) and [npm](https://www.npmjs.com/). Npm is the future though. I've updated the instructions to include `npm install` when getting started. This will add meteor-later and then things should work. @EdwardKepler, let me know if you come across any further issues.
