### ISSUE TITLE
Swap out Sass for Stylus

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#2]
[Stylus](https://learnboost.github.io/stylus/), while a cool project, is a lot less popular than [SASS](http://sass-lang.com/), and do to multiple people being confused where the style-sheets were... we should swap Stylus out for SASS. IMHO, not much is gained by using Stylus over SASS, except confusing people.

**Comment by arcalinea** [comment]
Closed by #4
