### ISSUE TITLE
Better visualization UI

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#207]
- [x] Increase font size on values
- [ ] Add some padding to auto scaling
- [ ] Create default chartist.js options for common data types: temperature, pH, humidity, etc.
- [x] Gauge component
- [ ] Make gauge component actually look nice.

**Comment by JakeHartnell** [comment]
http://grafana.org/

**Comment by cloudzombie** [comment]
I stumbled onto this, https://epochjs.github.io/epoch/ Real time Visualizations and an old un-updated meteor package for it https://github.com/pfafman/meteor-epoch
