### ISSUE TITLE
Time series

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#211]
Might need some help with this, but it will be very useful for analytics. Links:

https://themeteorchef.com/snippets/aggregations-in-mongodb/
https://www.youtube.com/watch?v=BC75qASfeFw

**Comment by JakeHartnell** [comment]
https://influxdata.com/

**Comment by cloudzombie** [comment]
What about [RethinkDB](https://www.rethinkdb.com/) ? 

realtime JSON format, time series etc.

**Comment by JakeHartnell** [comment]
Readings:
- http://blog.mongodb.org/post/65517193370/schema-design-for-time-series-data-in-mongodb
- https://github.com/gionkunz/chartist-js/issues/116

**Comment by JakeHartnell** [comment]
@mitar do you know of any good blog posts / articles for doing time series with Mongo off the top of your head?

**Comment by mitar** [comment]
That one above you linked.

Maybe @kostko has some idea as well what would be the best to use from Meteor for time series.

**Comment by JakeHartnell** [comment]
Thanks @mitar!

**Comment by kostko** [comment]
I would look into InfluxDB for time series as it stores data very compactly using its TSM storage engine. Not sure about the JS API client, but the protocol is really simple, so it should be easy to implement if needed.

**Comment by JakeHartnell** [comment]
> Not sure about the JS API client, but the protocol is really simple, so it should be easy to implement if needed.

+1

Another good thing about InfluxDB is that it works with grafana: http://www.grafana.org/

There is enough to do already, I don't really feel like diving into D3 at the moment to create pretty / powerful visualizations....

**Comment by JakeHartnell** [comment]
> Not sure about the JS API client, but the protocol is really simple, so it should be easy to implement if needed.

+1

Another good thing about InfluxDB is that it works with grafana: http://www.grafana.org/

There is enough to do already, I don't really feel like diving into D3 at the moment to create pretty / powerful visualizations....

**Comment by mitar** [comment]
Does InfluxDB support reactivity?

**Comment by JakeHartnell** [comment]
Another possibility might be using elasticsearch... http://docs.grafana.org/datasources/elasticsearch/

https://hharnisc.github.io/2015/06/29/enhancing-meteor-with-elasticsearch.html#1

**Comment by JakeHartnell** [comment]
https://github.com/prometheus/prometheus

**Comment by JakeHartnell** [comment]
Closing in favor of #313
