### ISSUE TITLE
Connect Raspberry Pi

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#215]
Document how to get started with Grow-IoT and Raspberry pi.

**Comment by EdwardKepler** [comment]
Thanks

**Comment by JakeHartnell** [comment]
How's this for a start? https://github.com/CommonGarden/Grow-IoT/wiki/Raspberry-Pi

Any suggestions for improvements? I don't have a raspberry pi at the moment, but am getting one soon to test this.

**Comment by JakeHartnell** [comment]
Has anyone had success with these instructions? https://github.com/CommonGarden/Grow-IoT/wiki/Raspberry-Pi

Hopefully, we'll be getting some Pis soon...

**Comment by JakeHartnell** [comment]
Ok, closing this because I like to keep issue trackers clean. : )

Feel free to reopen if the instructions aren't good enough.
