### ISSUE TITLE
Taking some time to research and build a team

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#223]
This is currently a prototype mostly useful for my own purposes in building demos and trying to gain some insight into [Cyber-Physical Systems](http://cyberphysicalsystems.org/). It's time to make this into a real open source project, and for that it means more than just me working on the project. So pardon while I take some time to build a team and raise some funds... we'll ultimately move much faster than me working by myself.
# OpenAgriculture is going places; we need to feed 9 billion people without destroying the planet after all.

We are looking for partnerships, collaborators, contributors, etc. Hit me up at Jake at commongarden.org

Stay tuned, @CommonGarden will be launching shortly. Feel free to open new issues for discussion. ; )

**Comment by extrapixel** [comment]
Hi Jake, I would love to talk. You can contact me via our contact form (www.whiteboxes.ch/contact)

**Comment by JakeHartnell** [comment]
Back to work.
