### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#228]
Let's connect to a device over bluetooth. This is a good hack project as it is kind of tangential to the rest of the work going on... and yet communicating with Bluetooth devices would be extremely useful.

For inspiration, the http://ruuvitag.com/ is pretty cool. Thanks to @cloudzombie for linking to this wonderful video (feel free to skip to 2 minutes in): https://www.youtube.com/watch?v=3Qd2GngIAkA

https://google.github.io/physical-web/
https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web
https://elements.polymer-project.org/elements/platinum-bluetooth
https://github.com/google/eddystone

**Comment by EdwardKepler** [comment]
This is awesome

**Comment by JakeHartnell** [comment]
Any interesting links with regards to either working with bluetooth on the Raspberry Pi 3 (preferably in node), or the emerging web bluetooth api would be awesome!

For inspiration, the http://ruuvitag.com/ is pretty cool. Thanks to @cloudzombie for linking to this wonderful video (feel free to skip to 2 minutes in): https://www.youtube.com/watch?v=3Qd2GngIAkA

**Comment by JakeHartnell** [comment]
> This is awesome

I agree. It would be cool to use the Raspberry Pi 3 as a hub for cheaper / low power devices. : )

**Comment by JakeHartnell** [comment]
We won't forget about adding bluetooth, but let's wait until Polymer 2.0 comes out.

**Comment by JakeHartnell** [comment]
Reopening, as we're now using web components so it will be easier to experiment.

**Comment by JakeHartnell** [comment]
Adding the ux label because this will be very useful for improving thing setup experience (especially for devices like the Raspberry Pi or C.H.I.P that have both bluetooth and wifi).

See https://github.com/CommonGarden/Grow-IoT/issues/277

**Comment by JakeHartnell** [comment]
Will revisit this soon hopefully.
