### ISSUE TITLE
Web component architecture

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#241]
Ok, for alpha we're going to use web components.

Why? Largely, because web components are being implemented in modern browsers and the polyfills are pretty decent by this point. However, I think most interestingly is the possibility of using web components with Internet of Things devices. Grow-IoT is all about interoperability, and after some experimenting I believe the modularity of web components will map very nicely to 'things'.

In other words, rather than hardware makers having to create a whole app for their device they can make a much smaller component that can be inoperable between apps... more thoughts on this later.

What do you think?

Some awesome projects to check out:
https://github.com/meteorwebcomponents
https://github.com/meteorwebcomponents/synthesis
https://github.com/meteorwebcomponents/layout
https://github.com/meteorwebcomponents/mixin
https://github.com/aruntk/kickstart-meteor-polymer

Further rational: https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f#.bo5watix4

**Comment by aruntk** [comment]
@JakeHartnell Importing files from public like [this](https://github.com/CommonGarden/Grow-IoT/blob/alpha/imports/ui/components/test-element.html#L1) will not work. Synthesis interprets this as `import "./public/bower_components/polymer/polymer.html"`, which means `imports/ui/components/public/bower_components/polymer/polymer.html`. If you want to import scripts or stylesheets or html from public use `src="/path/to/my/file"`.

I've created a [boiler-plate app](https://github.com/aruntk/kickstart-meteor-polymer). The strategy I'm adopting is to add an [imports.html](https://github.com/aruntk/kickstart-meteor-polymer/blob/master/public/imports.html) file in public with all the link imports and vulcanize this file to [imports/ui/build.html](https://github.com/aruntk/kickstart-meteor-polymer/blob/master/imports/ui/build.html). Then I import the build file in [ui/index.js](https://github.com/aruntk/kickstart-meteor-polymer/blob/master/imports/ui/index.js#L1) file. One advantage of this method is to reduce the number of files meteor has to track. Your startup time will be reduced if you reduce the number of js files . Check this [issue](https://github.com/meteor/meteor/issues/6859) for more info. 

vulcanize command `vulcanize --inline-css --inline-scripts --strip-comments public/imports.html > imports/ui/build.html`

If you are interested check [polymer apollo package](https://github.com/aruntk/polymer-apollo) for apollo-graphql support. :)

**Comment by JakeHartnell** [comment]
Closing this issue as it is broad and not very specific.
