### ISSUE TITLE
Add eslint exceptions

### ISSUE THREAD

**Issue by newswim** [CommonGarden/Grow-IoT#267]
### Expected Behavior.

ESLint should not warn about Meteor globals or complain about Node and/or testing environments.
### Actual Behavior.

ESLint hates these things.
### Steps to reproduce the behavior.

Run the project with either a local or global instance of ESLint, I'm using:

```
➜  ~ eslint --version
v3.8.1
```
### Conclusion

Package.json indicates `"eslint": "^2.11.1"`.

I would like to update the ESLint version and add headers to appease the parser. This acceptable?

**Comment by newswim** [comment]
https://guide.meteor.com/code-style.html#eslint-installing

**Comment by JakeHartnell** [comment]
> I would like to update the ESLint version and add headers to appease the parser. This acceptable?

Yes!

**Comment by JakeHartnell** [comment]
Ok, cleaned this up with https://github.com/CommonGarden/Grow-IoT/commit/f5cb465e7558f2318e92fa246f59550bf62116c9 and https://github.com/CommonGarden/Grow-IoT/commit/ff2733e6e6e99c0fa0a4b52180ba6a65b097e000. Thanks for pointing it out.
