### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#268]
We need web components for the following:
- [x] Temperature
- [ ] Humidity
- [ ] CO2
- [x] pH
- [ ] Conductivity
- [ ] Dissolved oxygen

We are working on them here: https://github.com/CommonGarden/Grow-Elements

When they're ready we'll publish to bower and add them to Grow-IoT. People might find them useful for other projects.

Feel free to suggest existing web components that we could potential use (or make one).

I've started including these in the `imports/things/test-thing.html` component, shown here:

![workspace 1_017](https://cloud.githubusercontent.com/assets/521978/20084015/98061fc8-a514-11e6-8778-3de85abd98d5.png)

The basic idea of Grow-IoT is to make it easier to create a web interface for an IoT device. You can add many kinds of custom devices to the dashboard.

![grow_example](https://cloud.githubusercontent.com/assets/521978/20240422/a50694ee-a8cc-11e6-97f5-81b636149b85.png)

**Comment by JakeHartnell** [comment]
Will eventually break these out into a separate repo and publish on bower....

**Comment by JakeHartnell** [comment]
https://github.com/CommonGarden/Grow-IoT/issues/271

**Comment by JakeHartnell** [comment]
The basic idea of Grow-IoT is to make it easier to create a web interface for an IoT device. You can add many kinds of custom devices to the dashboard.

![grow_example](https://cloud.githubusercontent.com/assets/521978/20240422/a50694ee-a8cc-11e6-97f5-81b636149b85.png)

**Comment by jermspeaks** [comment]
Temperature Gauge

<img width="377" alt="screen shot 2016-11-13 at 11 56 16 am" src="https://cloud.githubusercontent.com/assets/7095290/20248398/3d3e2c10-a998-11e6-915f-86ba965ea85f.png">
[Repo](https://github.com/jermspeaks/temperature-gauge/releases/tag/v0.0.1)

**Comment by jermspeaks** [comment]
pH Indicator: [Repo](https://github.com/jermspeaks/ph-indicator/releases/tag/v0.0.1)

<img width="339" alt="screen shot 2016-11-13 at 12 14 07 pm" src="https://cloud.githubusercontent.com/assets/7095290/20248519/b4235f56-a99a-11e6-9729-9d5b65bf703f.png">

**Comment by jermspeaks** [comment]
Much needed update to the Temperature Gauge. Please update. [Latest Release](https://github.com/jermspeaks/temperature-gauge/releases/tag/v0.1.1)

<img width="378" alt="screen shot 2016-11-14 at 9 27 48 pm" src="https://cloud.githubusercontent.com/assets/7095290/20294192/3b758530-aab1-11e6-864b-6269babc112b.png">

**Comment by JakeHartnell** [comment]
@jermspeaks looking good!

Care to make a PR on the grow-elements repo? https://github.com/CommonGarden/grow-elements

I think it makes sense to curate a collection of elements useful for smart growing systems.

**Comment by JakeHartnell** [comment]
Closing in favor of https://github.com/CommonGarden/grow-elements/issues/3
