### ISSUE TITLE
State container for managing predictable data.

### ISSUE THREAD

**Issue by aruntk** [CommonGarden/Grow-IoT#270]
Proposal

Use redux as a global state container. https://github.com/tur-nr/polymer-redux

This will make the data flow more predictable hence controllable and manageable.

**Comment by aruntk** [comment]
@JakeHartnell I've implemented this in one of my apps. Its really helpful for large apps. I'll start with a global state to display and log errors. :)

**Comment by JakeHartnell** [comment]
> @JakeHartnell I've implemented this in one of my apps. Its really helpful for large apps. I'll start with a global state to display and log errors. :)

Cool, go for it. :+1:
