### ISSUE TITLE
Build freezes at building for web.browser

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#279]
So recently updated things and now Grow-IoT freezes on `Building for web.browser` on both my linux laptop and mac.

Saw this previous issue, it may be related? https://github.com/meteor/meteor/issues/6859

@aruntk any thoughts on this? Did I do something dumb?

From what I can tell, the trouble started with this commit: https://github.com/CommonGarden/Grow-IoT/commit/e90925cdc0ee244edfca4deeaf299f7fe21a0f2a

**Comment by aruntk** [comment]
This folder might be the reason. I'll check for more ways to speed up build. https://github.com/CommonGarden/Grow-IoT/tree/alpha/imports/ui/bower_components/grow-elements/bower_components

**Comment by aruntk** [comment]
I've added a build file and created a pr to fix this issue.

https://github.com/CommonGarden/Grow-IoT/blob/issue-279/build.sh

**Comment by JakeHartnell** [comment]
Thanks!

**Comment by JakeHartnell** [comment]
I'll try to clean up [grow-elements](https://github.com/CommonGarden/grow-elements) a bit...
