### ISSUE TITLE
NPM Fail

### ISSUE THREAD

**Issue by EdwardKepler** [CommonGarden/Grow-IoT#281]
### Expected Behavior.
NPM install on .build.sh

### Actual Behavior.
web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install"
npm ERR! node v4.6.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/edwardkepler/Grow-IoT/Grow-IoT/npm-debug.log
NPM installation failed.!

### Steps to reproduce the behavior.
Mac Book Pro

**Comment by aruntk** [comment]
https://github.com/CommonGarden/Grow-IoT/blob/alpha/build.sh#L23

Command is just the meteor npm install. Maybe a timeout issue. Works fine in my system.

**Comment by JakeHartnell** [comment]
Can't reproduce, feel free to reach out on Gitter or reopen this issue if problems persist.
