### ISSUE TITLE
Remember sort order

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#283]
### Expected Behavior.
If change the order of things and reload the page, they should be in the order I placed them in.

### Actual Behavior.
Reloading the page resets everything to how it was.

### Steps to reproduce the behavior.
Make a few new things, mix up the order, and reload. 

### Other notes
https://github.com/CommonGarden/Grow-IoT/issues/264 is still relevant.

**Comment by aruntk** [comment]
This is a bit tricky to achieve if you are planning to add filters. Is it necessary to make things sortable? I think its better to have an option to give custom names to things and add a filter search box. @JakeHartnell thoughts?

**Comment by JakeHartnell** [comment]
> I think its better to have an option to give custom names to things and add a filter search box.

That would work!

**Comment by aruntk** [comment]
@JakeHartnell I'll work on this. Any other issue to look at?

**Comment by JakeHartnell** [comment]
>  Any other issue to look at?

Soon! There is [timeseries](https://github.com/CommonGarden/Grow-IoT/issues/211), and there are many potential ways of tackling that... there has already been some discussion!
