### ISSUE TITLE
Use app-route?

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#286]
Should we move away from flow-router? @aruntk suggested app-route:
https://elements.polymer-project.org/elements/app-route
https://www.polymer-project.org/1.0/toolbox/routing

On a sidenote: I was thinking we could have routes then for rendering particular web components like `test-thing` or `test-device.` Relevant code is in `imports/ui/components/dashboard/thing-display.html`.

**Comment by aruntk** [comment]
https://github.com/CommonGarden/Grow-IoT/tree/issue-286
