### ISSUE TITLE
weather-icons fail to load

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#294]
### Problem
![selection_024](https://cloud.githubusercontent.com/assets/521978/21212239/a8ba60f2-c23f-11e6-8194-505a4b9837b2.png)

Firefox console:
```
downloadable font: rejected by sanitizer (font-family: "weathericons" style:normal weight:normal stretch:normal src index:1) source: http://localhost:3000/font/weathericons-regular-webfont.woff  
downloadable font: rejected by sanitizer (font-family: "weathericons" style:normal weight:normal stretch:normal src index:2) source: http://localhost:3000/font/weathericons-regular-webfont.ttf
```
Chrome console:
```
Failed to decode downloaded font: http://localhost:3000/font/weathericons-regular-webfont.woff
OTS parsing error: invalid version tag
Failed to decode downloaded font: http://localhost:3000/font/weathericons-regular-webfont.ttf
OTS parsing error: invalid version tag
```

### Steps to reproduce 
1. Click the "+" button to make a new thing
2. Select the "Create test thing" option
3. Enter `weather-widget` as the component to render.

**Comment by aruntk** [comment]
Related to https://github.com/meteorwebcomponents/synthesis/issues/18

Workaround is to move assets to public folder.

**Comment by aruntk** [comment]
icons not working correctly.

Current version

<img width="407" alt="screen shot 2017-01-07 at 2 52 06 pm" src="https://cloud.githubusercontent.com/assets/6007432/21740754/e8af6dd6-d4e8-11e6-9419-39e8a7487971.png">


Desired o/p

<img width="382" alt="screen shot 2017-01-07 at 2 50 54 pm" src="https://cloud.githubusercontent.com/assets/6007432/21740759/f8c8604c-d4e8-11e6-9543-23d01088807c.png">
