### ISSUE TITLE
Elasticsearch syncing

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#302]
Searching is going to be important! Also with elastic search comes optional support for things like [Kibana](https://www.elastic.co/products/kibana) and [Grafana](http://grafana.org/) which would help resolve #211.

https://hharnisc.github.io/2015/06/29/enhancing-meteor-with-elasticsearch.html#1
https://github.com/toystars/elasticsearch-sync/

**Comment by aruntk** [comment]
@JakeHartnell A basic implementation as in the doc you shared. 

https://github.com/CommonGarden/Grow-IoT/tree/elastic-search

<img width="1280" alt="screen shot 2016-12-21 at 8 45 12 pm" src="https://cloud.githubusercontent.com/assets/6007432/21394406/886d2f8a-c7be-11e6-80b0-bee58fe944fe.png">

<img width="1280" alt="screen shot 2016-12-21 at 9 00 43 pm" src="https://cloud.githubusercontent.com/assets/6007432/21394924/92ff5304-c7c0-11e6-9550-598b8fdf1303.png">

**Comment by JakeHartnell** [comment]
Elastic search syncing is working great, but I think we broke something in the process:

![selection_028](https://cloud.githubusercontent.com/assets/521978/21468672/975a82ae-c9e4-11e6-86b3-25b3f0ffa99a.png)

Console:
```
TypeError: exists is not a function(…)
111768Uncaught TypeError: BSON is not a constructor(…)
Server @ modules.js?hash=dc8f4ac…:111768Server @ modules.js?hash=dc8f4ac…:103892(anonymous function) @ modules.js?hash=dc8f4ac…:103145translateOptions @ modules.js?hash=dc8f4ac…:103142createServer @ modules.js?hash=dc8f4ac…:103165connect @ modules.js?hash=dc8f4ac…:103292MongoClient.connect @ modules.js?hash=dc8f4ac…:103082(anonymous function) @ modules.js?hash=dc8f4ac…:89376run @ modules.js?hash=dc8f4ac…:187074(anonymous function) @ modules.js?hash=dc8f4ac…:187088Collection._getCollection @ modules.js?hash=dc8f4ac…:89557Collection.getIndexes @ modules.js?hash=dc8f4ac…:89766exports.index @ modules.js?hash=dc8f4ac…:89000Queue @ modules.js?hash=dc8f4ac…:88870Connection.queue @ modules.js?hash=dc8f4ac…:88711meteorInstall.imports.api.elastic.queue.js @ queue.js:5fileEvaluate @ modules-runtime.js?hash=637cb12…:191require @ modules-runtime.js?hash=637cb12…:116Mp.import @ modules.js?hash=dc8f4ac…:314meteorInstall.imports.api.elastic.observe.js @ observe.js:1fileEvaluate @ modules-runtime.js?hash=637cb12…:191require @ modules-runtime.js?hash=637cb12…:116Mp.import @ modules.js?hash=dc8f4ac…:314meteorInstall.imports.api.elastic.index.js @ index.js:1fileEvaluate @ modules-runtime.js?hash=637cb12…:191require @ modules-runtime.js?hash=637cb12…:116Mp.import @ modules.js?hash=dc8f4ac…:314meteorInstall.imports.api.index.js @ index.js:1fileEvaluate @ modules-runtime.js?hash=637cb12…:191require @ modules-runtime.js?hash=637cb12…:116Mp.import @ modules.js?hash=dc8f4ac…:314meteorInstall.client.main.js @ main.js:1fileEvaluate @ modules-runtime.js?hash=637cb12…:191require @ modules-runtime.js?hash=637cb12…:116(anonymous function) @ app.js?hash=ec5167b…:42526
```

**Comment by aruntk** [comment]
@JakeHartnell Everything seems to be fine in my system. How can I recreate the error?

**Comment by JakeHartnell** [comment]
Hmmm, sorry, forgot steps to reproduce.

1. Create a new thing (click the `+` button).
2. Click 'Create test thing' or connect the test device.

**Comment by aruntk** [comment]
@JakeHartnell unable to recreate the issue. Could you check again or maybe try resetting the db?

**Comment by JakeHartnell** [comment]
Resetting the db worked! Thanks!

**Comment by aruntk** [comment]
@JakeHartnell  Great. :). Could you please come online on gitter?
