### ISSUE TITLE
Sandstorm support

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#304]
It would be soooo cool if Grow-IoT worked with [Sandstorm](https://sandstorm.io/). @tilgovi @mitar @aruntk

**Comment by JakeHartnell** [comment]
see https://github.com/peer/mind

**Comment by mitar** [comment]
Yes, it would be interesting to have it. :-)

**Comment by aruntk** [comment]
Related issue https://github.com/sandstorm-io/sandstorm/issues/2810

**Comment by aruntk** [comment]
@JakeHartnell Sandstorm spk successfully created. https://drive.google.com/file/d/0B_N4Uc16m5v-SklQWTZWSlRPZFE/view?usp=sharing . Try it with local sandstorm.

Before uploading to sandstorm app store change https://github.com/CommonGarden/Grow-IoT/blob/sandstorm/.sandstorm/sandstorm-pkgdef.capnp and add pgp signature and keyring.

**Comment by JakeHartnell** [comment]
Well, we've started this. More testing is needed but I'm closing this for now! Thanks @aruntk!

**Comment by JakeHartnell** [comment]
Ok, this probably needs to be revisited as we are nearing v0.4
