### ISSUE TITLE
InfluxDB for events data

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#313]
I want to have the option of storing timestamped event data in InfluxDB.

Node client: https://github.com/node-influx/node-influx

**Comment by EdwardKepler** [comment]
Me Too

**Comment by EdwardKepler** [comment]
Grafana

**Comment by JakeHartnell** [comment]
https://github.com/node-influx/node-influx

**Comment by JakeHartnell** [comment]
This *might* help: https://github.com/electronifie/metrics-influxdb/blob/devel/index.js

**Comment by JakeHartnell** [comment]
This has been requested a few times by a few clients, it would be good for the demo if we could also show off a [Grafana](https://grafana.com/) dashboard for viewing time-series event data.

**Comment by JakeHartnell** [comment]
Ok, this works on development. If someone wants to review this that would be great, I'll work to document.

**Comment by JakeHartnell** [comment]
![grow-data](https://cloud.githubusercontent.com/assets/521978/25785182/4bea3d82-332f-11e7-9ba3-e1b1850fbab9.jpg)
