### ISSUE TITLE
React

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#319]
@aruntk brought this up in #315, probably best to do this sooner rather than later? The application is pretty simple at this point...

**Comment by aruntk** [comment]
I'll try to create a basic react based front end for the graphql and rest backends.

**Comment by aruntk** [comment]
Started a repo. https://github.com/aruntk/grow-iot-react. Started with [next.js](https://github.com/zeit/next.js) as the framework. I'll port the features of this app to it, and once it is complete we can think about merging into the current grow-iot app.

**Comment by JakeHartnell** [comment]
https://facebook.github.io/react/docs/web-components.html

**Comment by JakeHartnell** [comment]
New react branch for peeps to try out: https://github.com/CommonGarden/Grow-IoT/tree/react

Thanks @aruntk!

**Comment by JakeHartnell** [comment]
Alright, we're using react with development so closing.
