### ISSUE TITLE
Get Travis CI working

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#322]

**Comment by camillevilla** [comment]
Hey! I've been working with Travis a lot lately. I've only been using it in Rails, not Node, but would love to take a shot at getting this set up.

**Comment by JakeHartnell** [comment]
@camillevilla cool! Shouldn't be too different. Just need a `travis.yml` file, and here's info on customizing it for node: https://docs.travis-ci.com/user/languages/javascript-with-nodejs

**Comment by camillevilla** [comment]
@JakeHartnell can you tell me more about what `LAIKA_OPTIONS="-t 5000` is accomplishing in the .travis.yml file? A comment about the `before_install` curl command would be helpful too.

I was able to get [a successful build job](https://travis-ci.org/CommonGarden/Grow-IoT) by [using a newer version of g++ in our .travis.yml. ](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements)

Here's the error message for future reference: 
> Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM.

**Comment by camillevilla** [comment]
And here's the branch I'm working on: 
https://github.com/CommonGarden/Grow-IoT/tree/travis-config

**Comment by JakeHartnell** [comment]
Build passing! Yay! Thanks for looking into this @camillevilla.
