### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#334]
Suggest them here!

**Comment by EdwardKepler** [comment]
drop down on card
![ph sensor -connectbox](https://cloud.githubusercontent.com/assets/15167277/24432121/9c890c78-13e5-11e7-9859-a1f35c80a90b.png)

**Comment by EdwardKepler** [comment]
IoT Connect Workflow
![ph sensor collectbox](https://cloud.githubusercontent.com/assets/15167277/24432271/ad3137a2-13e6-11e7-98c0-6320e20bf2d7.jpeg)

**Comment by EdwardKepler** [comment]
Correct Workflow
![ph sensor-correctbox](https://cloud.githubusercontent.com/assets/15167277/24432401/a0c77c32-13e7-11e7-854a-9776e93e711a.jpg)

**Comment by EdwardKepler** [comment]
Image Grid
![grow-iot home-8](https://cloud.githubusercontent.com/assets/15167277/24455735/52f160da-1456-11e7-9168-7b9fc1e805f8.jpg)

**Comment by JakeHartnell** [comment]
No comments in a couple of months, so closing for now. Feel free to reopen or create issues for feature requests.
