### ISSUE TITLE
Grow-Hub improvements

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#339]
- [x] Fix being unable to select text fields bug
- [x] Communicate weather temp values are in F or C
- [x] Edit Alerts (set alert for temperature low, etc.)
- [x] Add camera! It would be cool to see images of the Grow Room
- [ ] Make it prettier
- [x] Make it more responsive. Looks ok on large tablets, but not so good on smaller screens.

Current UI:
![makerpicture](https://cloud.githubusercontent.com/assets/521978/24823129/316d1ac4-1bb0-11e7-81a0-7df6f5ca4ef5.png)

Yes, that is a picture of the ceiling... still need to figure out how best to mount the camera...

Anyway, feel free to suggest improvements!

**Comment by EdwardKepler** [comment]
Awesome Love The Power Stats. Was going to ask for that

**Comment by EdwardKepler** [comment]
<img width="631" alt="grow mobile power" src="https://cloud.githubusercontent.com/assets/15167277/24823662/b18579b6-1bc6-11e7-8afe-8a7719201023.png">

Grid/Battery Maybe?

**Comment by JakeHartnell** [comment]
Update:
![grow_iot](https://cloud.githubusercontent.com/assets/521978/25060230/2aec41aa-214d-11e7-9498-a05d35f733c7.jpg)

**Comment by JakeHartnell** [comment]
Currently we're using another raspberry pi for the camera... anyone know of a good usb or bluetooth camera?
