### ISSUE TITLE
Styling Issue

### ISSUE THREAD

**Issue by EdwardKepler** [CommonGarden/Grow-IoT#344]
Grow Hub Styling Issue
<img width="1434" alt="screen shot 2017-04-09 at 8 45 18 pm" src="https://cloud.githubusercontent.com/assets/15167277/24844133/217ee150-1d6e-11e7-84e2-927a9d990861.png">

**Comment by EdwardKepler** [comment]
Firefox and safari on the mac

**Comment by aruntk** [comment]
@JakeHartnell -> To reproduce this issue, clear images collection. When there is an image in the collection everything gets rendered as expected.

**Comment by JakeHartnell** [comment]
Ah, yeah will fix this easy... I've been working with Images so I didn't notice.

**Comment by JakeHartnell** [comment]
![fix](https://cloud.githubusercontent.com/assets/521978/24880217/756b5cfa-1dee-11e7-9959-95c9aa29a85b.jpg)
