### ISSUE TITLE
Easily add custom things

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#345]
In the Latest tagged release of Grow-IoT we use Polymer and had better instructions for how to create custom things... the current documentation needs an update. It's as simple as making a react component or web component (yes, I want to support both).

**As a developer making an interface for a device, I want to be able to easily add my component to a Grow-IoT instance.**

- [x] Better documentation about this
- [x] Make it as easy as `npm install --save example-component` and add import it in `imports/things/index.js`
- [ ] Make a script that does this?

**Comment by EdwardKepler** [comment]
Yes Great Add!! Agree Totally

**Comment by JakeHartnell** [comment]
https://github.com/CommonGarden/Grow-IoT/tree/things
