### ISSUE TITLE
Add And Delete Listeners To Things

### ISSUE THREAD

**Issue by EdwardKepler** [CommonGarden/Grow-IoT#346]
It Would be nice to be able to have One Thing Be able to subscribe to Another Thing's Topics and Act Accordingly.

![ec - pump3](https://cloud.githubusercontent.com/assets/15167277/24890396/4b2bf07a-1e35-11e7-942a-23bbeb33e338.jpg)

**Comment by JakeHartnell** [comment]
This is coming, but there is lots of UI work to do before this happens, so closing for now.
