### ISSUE TITLE
Min PH, Ideal PH in Grow Recipe.

### ISSUE THREAD

**Issue by EdwardKepler** [CommonGarden/Grow-IoT#349]
Is there a need for a Max PH or does that become the Ideal PH.

**Comment by JakeHartnell** [comment]
If you want to just monitor ph (and balance it yourself) you just need min / max (to set alerts), if you're going to build an automated dosing system, ideal is super helpful.

This is actually already done in Grow.js, just not super well documented. I will change that soon.
