### ISSUE TITLE
Use prop-types package warning

### ISSUE THREAD

**Issue by aruntk** [CommonGarden/Grow-IoT#363]
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

related pr - https://github.com/esnet/react-timeseries-charts/pull/152

**Comment by JakeHartnell** [comment]
Awesome, I was wondering where the warning was still coming from.

**Comment by aruntk** [comment]
Meanwhile install this locally to remove the error (if you have a demo or something). https://drive.google.com/file/d/0B_N4Uc16m5v-NWF4ZGFUbmlESmc/view?usp=sharing
