### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#374]
Taking pictures of plants is super useful. Let's enable it, HTML5 makes that fairly easy:

https://coderwall.com/p/epwmoa/html5-mobile-device-camera-access
https://www.html5rocks.com/en/tutorials/getusermedia/intro/

**Comment by JakeHartnell** [comment]
https://github.com/mozmorris/react-webcam

**Comment by JakeHartnell** [comment]
What we really need for this is image upload, modern phone browsers allow you to take a photo or video! Recently tested this at a hackathon with: https://github.com/dreossi/canapest/

**Comment by catbarph** [comment]
@JakeHartnell does this have any overlap with webcam/timelapse functionality, or is just file upload?

**Comment by JakeHartnell** [comment]
This is done.
