### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#393]
I've gotten feedback that getting started is confusing and I think that's because Thing.js and Grow.js are separate repos. They will continue to be seperate libraries published on npm, but including them here will make getting started easier.

On the plus side, it will also mean we won't have to set them up as seperate open collective projects.

Todo:
- [x] Merge Thing.js and Grow.js into this repo
- [x] Use [Lerna](https://github.com/lerna/lerna)
- [x] Switch to yarn

Thanks @tilgovi for the Lerna recommendation!

**Comment by JakeHartnell** [comment]
Reopening as there are still a few things that need to be addressed:

- [x] Grow.js tests are not passing
- [x] Make sure examples are working
- [x] Get meteor to ignore the examples folder
- [x] Update README to reflect monorepo organization

**Comment by JakeHartnell** [comment]
Failing tests... they work on the old repo at: https://github.com/JakeHartnell/Grow.js

```
  1) Grow.js "before each" hook for "should write state to file":
     TypeError: Class constructor Thing cannot be invoked without 'new'
      at new Grow (dist/Grow.js:110:97)
      at Context.<anonymous> (test/grow-test.js:47:24)

  2) Growfile test "before each" hook for "should load the database":
     TypeError: Class constructor Thing cannot be invoked without 'new'
      at new Grow (dist/Grow.js:110:97)
      at Context.<anonymous> (test/growfile-test.js:13:23)

  3) Grow.js "before each" hook for "should have cloned metadata":
     TypeError: Class constructor Thing cannot be invoked without 'new'
      at new Grow (dist/Grow.js:110:97)
      at Context.<anonymous> (test/thing-test.js:47:24)

```

Tests for the Thing.js package pass...

**Comment by tilgovi** [comment]
Weird. Curious what you find.

**Comment by JakeHartnell** [comment]
Fixed now. Looks like the problem was related to the `.babelrc` in the Grow.js folder.
