### ISSUE TITLE
Clear all notifications

### ISSUE THREAD

**Issue by catbarph** [CommonGarden/Grow-IoT#404]
Currently is a bit tedious to clear lots of notifications from the webapp/UI. Can we add a "clear all notifications" button?

**Comment by JakeHartnell** [comment]
I'm assigning a $50 bounty to this issue. To claim it, submit a PR implementing:
- [ ] a clear all notifications button on the all notifications page: https://github.com/CommonGarden/Grow-IoT/blob/development/imports/app/pages/AllNotifications.jsx
- [ ] a clear all notifications button in the dropdown
