### ISSUE TITLE
UI - event history - order & other minor UI fixes

### ISSUE THREAD

**Issue by catbarph** [CommonGarden/Grow-IoT#405]
1. Event History log should show the most recent entry nearest the top (believe it was this way before?) as opposed to the bottom. To me, this is more readable.

2. Fix needed for "Show full History" link (does not work currently).
 
3. Also, it would be nice if the control buttons all aligned to a grid, as opposed to the text labels enforcing the grid. Shortening the control labels/names is an easier workaround...

<img width="957" alt="screen shot 2017-09-27 at 4 19 15 pm" src="https://user-images.githubusercontent.com/3916616/30943073-890b1102-a3a3-11e7-8ace-3c1e3c4eeb6f.png">

<-- Love Grow-IoT? Please consider supporting our collective:
👉  https://opencollective.com/Grow-IoT/donate -->

**Comment by JakeHartnell** [comment]
UI has been updated, this should be addressed.
