### ISSUE TITLE
UI - spelling & rogue bracket

### ISSUE THREAD

**Issue by catbarph** [CommonGarden/Grow-IoT#406]
Air temperature on UI is misspelled.

There is a bracket seemingly out of place...

And the control button alignment needs a fix.

<img width="940" alt="screen shot 2017-10-02 at 7 31 31 am" src="https://user-images.githubusercontent.com/3916616/31082821-c4575be0-a744-11e7-8285-906035b31c13.png">

<-- Love Grow-IoT? Please consider supporting our collective:
👉  https://opencollective.com/Grow-IoT/donate -->

**Comment by catbarph** [comment]
Another typo + (same?) rogue bracket.

<img width="879" alt="screen shot 2017-10-02 at 10 14 56 am" src="https://user-images.githubusercontent.com/3916616/31089975-dc697e0a-a75a-11e7-9ef4-036b1b035176.png">

**Comment by JakeHartnell** [comment]
Should be fixed with #407
