### ISSUE TITLE
Notification overload bug

### ISSUE THREAD

**Issue by catbarph** [CommonGarden/Grow-IoT#433]
Getting tons of notifications as "Alert: undefined undefined" which I take to be coming from a disconnected sensor probe, just maybe.

The sheer quantity of notifications seems to have slowed down the UI significantly. #404 is related here.

**Comment by JakeHartnell** [comment]
Note, we need to flesh this issue out a bit more. I attempted to look into it, but I can't reproduce.

**Comment by JakeHartnell** [comment]
Closing until we figure out how to reproduce this.
