### ISSUE TITLE
Should Thing.js be an extension of Stream instead of Event Emitter?

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#434]
Open question for me. A stream is also an instance of an Event Emitter...

**Comment by JakeHartnell** [comment]
@mitar's original code that kicked all this off used streams. It's my bad for taking that out.

**Comment by newswim** [comment]
FWIW, I think events are more easy to reason about. Streams are certainly awesome, particularly when applied to FRP as [Cycle.js] has done, but part of the issue i think is that the two aren't interchangeable in the same way that other concepts might be.

Domenic's answer in [question on StackOverflow] contrasts some of the differences in terms of **pull**-based and **push**-based API's.

You could probably construct a decision table based on some metrics, eg. _single-consumer_ vs. _multi-consumer_, push vs. pull, etc.

It might be the case that both are used, in different use cases.

[Cycle.js]: https://cycle.js.org
[question on StackOverflow]: https://stackoverflow.com/questions/39439653/events-vs-streams-vs-observables-vs-async-iterators
