### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by newswim** [CommonGarden/Grow-IoT#435]
Year currently reads 2016. I'd add two points:

- Consider a range like, `2016 - present`
- Switch over to standard MIT for the nice _visible indicator_:

<img width="397" alt="screen shot 2018-01-09 at 9 25 18 pm" src="https://user-images.githubusercontent.com/6667096/34754483-ad0061d4-f583-11e7-9640-68701eeeff9b.png">

**Comment by JakeHartnell** [comment]
This should be an issue with GitHub for not giving Free-BSD licenses a visible indicator.

Tell you what, when someone from the [MIT Open Agricultural Initiative](https://www.media.mit.edu/groups/open-agriculture-openag/overview/) makes a successful pull request, I'll let them also change the license to MIT. ; )

**Comment by newswim** [comment]
Sounds keen !

I updated the dates either way. If that PR gets merged, I'll start a new one for fixing the Travis build.

**Comment by JakeHartnell** [comment]
Done.
