### ISSUE TITLE
Installing dependencies shows an OC error

### ISSUE THREAD

**Issue by newswim** [CommonGarden/Grow-IoT#436]
Everything installs just fine, but there's a kind of sad looking error from the post-install supplied by Open Collective.

<img width="547" alt="screen shot 2018-01-09 at 9 30 13 pm" src="https://user-images.githubusercontent.com/6667096/34754712-0869d5e0-f585-11e7-844b-d9342f47420e.png">

**Comment by JakeHartnell** [comment]
I'm not seeing this anymore... perhaps they fixed it on their end? `1.0.3` is still the most recent version of opencollective on npm.

Anyway, closing this for now. Feel free to reopen if error persists.
