### ISSUE TITLE
Utilize peerdb references

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#76]
@mitar, I'm having a little trouble getting [ReferenceFields](https://github.com/peerlibrary/meteor-peerdb#references) to work in the app. So during the hackday would love to go over them.

**Comment by mitar** [comment]
Can you explain a bit what are the issues?

**Comment by JakeHartnell** [comment]
I'm trying to make devices and plants contain a reference to their growing environment and visa versa.

When I try:

```
   class Environment extends share.BaseDocument
       @Meta
        name: 'Environment'
        fields: =>
          owner: @ReferenceField User, [], false
          devices: [@ReferenceField Device]
          plants: [@ReferneceField Plant]
```

I get:

```
E20160120-14:27:02.119(-8) (peerlibrary_peerdb.js:776) Not all delayed document definitions were successfully retried:
Environment from Environment()@http://localhost:3000/packages/core.js?990a3c06ab89c55c90b5c610e86ff01295126567:269:15logInBrowser @ logging.js:65
```

**Comment by JakeHartnell** [comment]
I feel like I am missing something obvious...

**Comment by mitar** [comment]
You are missing [this file](https://github.com/mitar/council-app/blob/master/packages/core/finalize-documents.coffee).

**Comment by JakeHartnell** [comment]
Thanks @mitar for your help at the hackathon! : )
